- name: Create storage account
  hosts: localhost
  gather_facts: false
  tasks:
   - name: create resource group
     azure_rm_resourcegroup:
      name: "tsf-test-rg"
      location: "West Europe"
      tags:
       from: ansible
   - name: create storage account
     azure_rm_storageaccount:
      resource_group: "tsf-test-rg"
      name: "tsfteststo"
      account_type: "Standard_LRS"
      tags:
       from: ansible