- name: Create storage account
  hosts: localhost
  gather_facts: false
  tasks:
   - name: create resource group
     azure_rm_resourcegroup:
      name: "{{ hostvars.resource_group_name }}"
      location: "{{ hostvars.location }}"
      tags:
       from: ansible
   - name: create storage account
     azure_rm_storageaccount:
      resource_group: "{{ hostvars.resource_group_name }}"
      name: "{{ hostvars.storage_name }}"
      account_type: "{{ hostvars.sku_name }}"
      tags:
       from: ansible