- name: Create storage account
  hosts: localhost
  gather_facts: false
  tasks:
   - name: create resource group
     azure_rm_resourcegroup:
      name: TestAnsiblePMO01
      location: westeurope
      tags:
       from: ansible
   - name: create storage account
     azure_rm_storageaccount:
      resource_group: TestAnsiblePMO01
      name: ztestaccountpmo001
      account_type: Standard_LRS