- name: Create storage account
  hosts: ansible-azure
  gather_facts: false
  tasks:
   - name: Module Variables ("vars")
     copy:
       content: "{{ vars | to_nice_json }}"
       dest: ~/templateARM/inventory/allvars1.json
   - name: Environment Variables ("environment")
     copy:
       content: "{{ environment | to_nice_json }}"
       dest: ~/templateARM/inventory/allvars2.json   
   - name: GROUP NAMES Variables ("group_names")
     copy:
       content: "{{ group_names | to_nice_json }}"
       dest: ~/templateARM/inventory/allvars3.json  
   - name: GROUPS Variables ("groups")
     copy:
       content: "{{ groups | to_nice_json }}"
       dest: ~/templateARM/inventory/allvars4.json 
   - name: HOST Variables ("hostvars")
     copy:
       content: "{{ hostvars | to_nice_json }}"
       dest: ~/templateARM/inventory/allvars5.json   