- name: Create storage account
  hosts: ansible-azure
  gather_facts: false
  tasks:
   - name: Module Variables ("vars")
     shell: echo "{{ vars | to_nice_json }}" > allvars1.json
     args:
       chdir: ~/templateARM/inventory   
   - name: Environment Variables ("environment")
     shell: echo "{{ environment | to_nice_json }}" > allvars2.json
     args:
       chdir: ~/templateARM/inventory    
   - name: GROUP NAMES Variables ("group_names")
     shell: echo "{{ environment | to_nice_json }}" > allvars3.json
     args:
       chdir: ~/templateARM/inventory  
   - name: GROUPS Variables ("groups")
     shell: echo "{{ groups | to_nice_json }}" > allvars4.json
     args:
       chdir: ~/templateARM/inventory  
   - name: HOST Variables ("hostvars")
     shell: echo "{{ hostvars | to_nice_json }}" > allvars5.json
     args:
       chdir: ~/templateARM/inventory   