- name: Create storage account
  hosts: ansible-azure
  gather_facts: false
  tasks:
   - name: Module Variables ("vars")
     debug: msg="{{ vars | to_nice_json }}"   
   - name: Environment Variables ("environment")
     debug: msg="{{ environment | to_nice_json }}"  
   - name: GROUP NAMES Variables ("group_names")
     debug: msg="{{ environment | to_nice_json }}"   
   - name: GROUPS Variables ("groups")
     debug: msg="{{ groups | to_nice_json }}"
   - name: HOST Variables ("hostvars")
     debug: msg="{{ hostvars | to_nice_json }}"   