- name: The inventory script
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run inventory
      shell: awx-manage inventory_import --custom --source=azure_webapp_rm.py --inventory-name=z-aim-pmo3-inventory --overwrite || true
