- name: The inventory script
  hosts: ansible-azure
  gather_facts: true
  tasks:
    - name: Fetch Repository (Git)
      shell: git fetch  
      args:
        chdir: ~/templateARM/inventory
    - name: Pull Repository (Git)
      shell: git pull
      args:
        chdir: ~/templateARM/inventory      
    - name: Upgrade azure webApps
      shell: python azure_webapp_rm.py --pretty > webAppInventory.json
      args:
        chdir: ~/templateARM/inventory
    - name: Upgrade azure Redis
      shell: python azure_redis_rm.py --pretty > RedisInventory.json
      args:
        chdir: ~/templateARM/inventory
    - name: Commit Repository (Git)
      shell: git commit -a -m 'Update Inventory {{ ansible_date_time.iso8601 }}'
      args:
        chdir: ~/templateARM/inventory      
    - name: Push Repository (Git)
      shell: git push
      args:
        chdir: ~/templateARM/inventory      
