- name: The inventory script
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch Repository (Git)
      shell: git fetch --all   
    - name: Reset Repository (Git)
      shell: git reset --hard
    - name: Pull Repository (Git)
      shell: git pull master          
    - name: Upgrade azure webApps
      shell: python azure_webapp_rm.py --pretty > webAppInventory.json
    - name: Upgrade azure Redis
      shell: python azure_redis_rm.py --pretty > RedisInventory.json
    - name: Commit Repository (Git)
      shell: git commit -a -m 'Update Inventory {{ ansible_date_time.iso8601 }}'    
    - name: Push Repository (Git)
      shell: git push      
