- name: The inventory script
  hosts: ansible-azure
  gather_facts: true
  tasks:
    - name: Fetch Repository (Git)
      shell: git fetch  
      args:
        chdir: ~/templateARM/inventory
    - name: Pull Repository (Git)
      shell: git pull
      args:
        chdir: ~/templateARM/inventory      
    - name: Upgrade azure inventory
      shell: python azure_full_rm.py --pretty > fullInventory.json
      args:
        chdir: ~/templateARM/inventory
    - name: Commit Repository (Git)
      shell: git commit -a -m 'Update Inventory {{ ansible_date_time.iso8601 }}'
      args:
        chdir: ~/templateARM/inventory      
    - name: Push Repository (Git)
      shell: git push
      args:
        chdir: ~/templateARM/inventory      
