- name: The inventory script
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: msg="Run inventory"
      command: tower-manage inventory_import --custom --source=azure_webapp_rm.py --inventory-name={{ item }} --overwrite
      with_items: my_inventories